
export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS'
export const GET_POKEMON_BY_ID = 'GET_POKEMON_BY_ID'
export const GET_POKEMON_BY_NAME = 'GET_POKEMON_BY_NAME' 
export const GET_TYPES = 'GET_TYPES'
export const POST_POKEMONS = 'POST_POKEMONS'

